### ISSUE TITLE
Loop View or Cylindrical view is not working with few aspect ratios

### ISSUE THREAD

**Issue by prudhvinag007** [naver/egjs-view360#391]
## Description

My Cylindrical panorama image dimensions are 10141 x 2741, when I use the Panoaram projection type, the view is not circular in motion. Are there any settings to force the viewer to automatically loop the entire image.
![22144-1656508622](https://user-images.githubusercontent.com/61545437/180252895-bb07bacf-6eaf-4cb8-ad5b-fb255cfcb7a6.jpg)

**Comment by prudhvinag007** [comment]
When I force resize this image to 10141 x 1648, it works.

**Comment by WoodNeck** [comment]
Cylindrical projection in `v3` determined whether it covers the panorama by image ratio.
If the image's width is bigger than its height by 6 times(> 6:1), like the above image, it treated the image as a full panorama image.

It is fixed in v4 by explicitly setting the option `partial` instead,
- https://naver.github.io/egjs-view360/docs/projections/cylindrical#partial
