### ISSUE TITLE
Providing 'release' event

### ISSUE THREAD

**Issue by happyhj** [naver/egjs-view360#43]
## Description
From the discussion below,
https://github.com/naver/egjs-view360/pull/42#discussion_r147877409
@jongmoon thinks providing 'release' event will help developing with PanoViewer.
But I do not know what kind of situation is like the 'release' event becoming useful.

Isn't it enough to use debounce method to 'change' event?

**Comment by jongmoon** [comment]
I've thought it for a moment. 

and I feel it gives confusion to user. because of motion event. Motion Event(&Device Orientation Event) doesn't have concept of 'release'(or `end` event). it is continuous event. it doesn't have 'end'(release) concept. YawPitchControl also started from that background. So YawPitchControl should expose interface as same concept.

If 'release' event is exposed, User of YawPitchControl should have confusion about release event.

**Comment by happyhj** [comment]
Okay, If we find that the case we need a "release" event, let's discuss it again.
